config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }

  resources :users, only: %i[index]

  resources :categories, only: %i[index show new create destroy] do
    resources :transactions, only: %i[new create destroy]
  end

  resources :starts, only: %i[index]
  root 'starts#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user || User.new
    if user.role == 'admin'
      can :manage, :all
    else
      can :manage, Category, user_id: user.id
      can :manage, Transaction, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy

  validates :name, presence: true, length: { in: 1..20 }
  validates :icon, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories
  has_many :transactions
  validates :name, presence: true, length: { in: 1..20 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :role, :password, :password_confirmation)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
    @transactions = @category.transactions.order(created_at: :desc)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # POST /categories or /categories.json
  def create
    category = Category.new(category_params)

    if category.save
      redirect_to categories_url, notice: 'Category created successfully.'
    else
      redirect_to categories_path, alert: 'Failed to create new category.'
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    if @category.destroy!
      flash[:notice] = 'Category deleted!'
      redirect_to categories_path
    else
      flash[:alert] = 'Failed to delete category!'
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def category_params
    category = params.require(:category).permit(:name, :icon, :user_id)
    category[:user_id] = current_user.id
    category
  end
end

app/controllers/sessions_controller.rb
# app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def respond_to_on_destroy
    respond_to do |format|
      format.all { head :no_content }
      format.any(*navigational_formats) { redirect_to after_sign_out_path_for(resource_name), status: :see_other }
    end
  end
end

app/controllers/starts_controller.rb
class StartsController < ApplicationController
  def index
    redirect_to users_path if user_signed_in?
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @category = Category.where(author_id: current_user.id)
  end

  # POST /transactions or /transactions.json
  def create
    transaction = Transaction.new(transaction_params)

    if transaction.save
      redirect_to category_url(transaction.category), notice: 'Transaction was successfully created.'

    else
      redirect_to category_url(transaction.category), notice: 'Failed to create new transaction'
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    transaction = Transaction.find(params[:id])

    if transaction.destroy!
      redirect_to categories_url, notice: 'Transaction was successfully deleted.'
    else
      redirect_to categories_url, notice: 'Faile to delete transaction.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    transaction = params.require(:transaction).permit(:name, :amount, :category_id)
    transaction[:user_id] = current_user.id
    transaction
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: %i[ show ]

  # GET /users or /users.json
  def index
    @users = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<%= link_to category do %>

  <div id="<%= dom_id category %>", class="category-flex">
    <img src="<%=category.icon %>" alt='category icon', class="icon"/>
   
    <p>
     <strong><%= category.name %></strong>
    </p>

    <p>
      <strong>$<%= category.transactions.sum(:amount)%></strong>
    </p>

  </div>
<% end %>

app/views/categories/_form.html.erb
<section  class=" form-transact" >   
  <%= form_with(model: category) do |form| %>

    <div>
      <%= form.text_field :name, placeholder: "Name", class:"input" %>
    </div>

    <div>
      <%= form.text_field :icon, placeholder: "Icon", class: "input" %>
    </div>

    <button class="save-b">
      <%= form.submit :save, class: "save" %>
    </button>
  <% end %>
</section>

app/views/categories/index.html.erb
<section>

  <% if @categories.exists? %>
    <div>
      <div class="top-nav">
        <p><%= link_to "User", users_path, class: "links"%></p>
        <h1>CATEGORIES</h1>
      </div>
        
      <% @categories.each do |category| %>
        <%= render category%><br>
      <% end %> 
    </div>

  <% else %> 
  <div class="logo">
    <p class="app_name">E-neza Transaction</p>
  </div>
  <% end %>

  <button class="flex-end-add">
    <%= link_to "Add Category", new_category_path, class: "add-cate" %>
  </button>

</section>

app/views/categories/new.html.erb
<section>

  <h1 class="new-category" >New category</h1>

  <div>
    <%= render "form", category: @category %>
  </div>
  
</section>

app/views/categories/show.html.erb
<section class="section-transaction" >
  <div>
      <div class="main-nav">
        <div class="top-nav">
          <p><%= link_to "Back", categories_path, class: "links"%></p>
          <h3>TRANSACTIONS on <%= @category.name%></h3>
          <p><%= link_to "User", users_path, class: "links"%></p>
        </div>

        <div class="trendz">
          <p><%= link_to "Most recent", categories_path, class: "links"%></p>
          <p>Most ancient</p>
        </div>
        
      </div>

      <div class="below-nav">
        <p> Total: $
        <strong><%= @category.transactions.sum(:amount) %></strong>
        </p>
        <%= button_to "Delete", @category, method: :delete, class: "delete" %>
      </div>

      

      <% if @transactions.exists? %>
        <div>
          <% @transactions.each do |transaction| %>
          <div> 
              <%= render transaction %>
            </div>
          <% end %>
        </div>
      <% else %>  
      <% end %>
  </div>
  <button class="flex-end">
   <%= link_to "Add Transaction", new_category_transaction_path(@category), class: "add-transaction" %>
  </button>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= yield %>

    <p class="alert"><%= alert %></p>
    <p class="notice"><%= notice %></p>

  </body>
</html>

app/views/starts/index.html.erb
<section class="on_start">
  
  <div class="logo">
    <p class="app_name">E-neza Transaction</p>
  </div>

  <div class="start">
    <p><%= link_to "Log in", new_user_session_path, class: "links"%></p>
    <p><%= link_to "Sign up", new_user_registration_path, class: "links" %></p>
  </div>

</section>

app/views/transactions/_form.html.erb
<section class=" form-transact" >
  <%= form_with(model: transaction, url: category_transactions_path(@category)) do |form| %>
    <div class="category-select">
      <%= form.label :category_id %>
      <%= form.collection_select :category_id, current_user.categories, :id, :name, prompt: true, class: 'bg-slate-50' %>
    </div>

    <div>
      <%= form.text_field :name, placeholder: "Name", class: "input" %>
    </div>

    <div>
      <%= form.number_field :amount, placeholder: "Amount", class: "input" %>
    </div>

    <button class="save-b">
      <%= form.submit :save, class: "save"%>
    </button>
  <% end %>
</section>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>", class="transaction-flex">

  <p>
    <strong><%= transaction.name %></strong>
  </p>
  
  <p>
  <strong>$<%= transaction.amount %></strong>
  </p>
</div>

app/views/transactions/new.html.erb
<section>

  <h1 class="new-category">New transaction</h1>
  <%= render "form", transaction: @transaction %>
  
</section>

app/views/users/index.html.erb
<section class="user">
  <div class="in_out">
    <p class="welcome_page">Welcome, <%= @users.name %></p>

    <p><%= link_to "Log out", destroy_user_session_path, data: { "turbo-method":
    :delete } %></p>
  </div>
 
  <div class="logo">
    <p class="app_name">E-neza Transaction</p>
  </div>

  <button class="flex-end-add">
    <%= link_to "Start", categories_path, class: "add-cate" %>
  </button>
</section>